name: CI/CD Pipeline

on:
  push:
    branches: [main, production]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies backend
        working-directory: ./backend
        run: npm install

      - name: Run backend tests (placeholder)
        working-directory: ./backend
        run: echo "No tests yet"

      - name: Install dependencies frontend
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm run test -- --watchAll=false || true

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Build Docker images
        run: docker-compose build

  deploy-production:
    needs: build-and-test
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t yourdockerhubuser/backend:latest ./backend
          docker push yourdockerhubuser/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t yourdockerhubuser/frontend:latest ./frontend
          docker push yourdockerhubuser/frontend:latest
